http
{
	server
	{
		listen 0.0.0.0:5500;
		server_name mde-prin.42.fr;
		root ~/cursus/webserv/shared;
		client_max_body_size 1;
		max_connections 2048;
		autoindex on;
		error_page 404 405 error/404.html;

		location /
		{
			index naviguation.html;
			client_max_body_size 1;
			cgi .php /usr/bin/php;
			cgi .js /usr/bin/node;
			methods POST GET;
		}

		location /alias
		{
			alias files;
		}

		location /files/
		{
			index upload.html;
			client_max_body_size 500;
			methods GET POST DELETE;
			cgi .php /usr/bin/php;
			cgi .sh /bin/bash;
		}

		location /upload
		{
			index upload.html;
			client_max_body_size 10k;
			methods GET;
		}
	}

	server
	{
		listen 127.0.0.1:8080;
		server_name mde-prin.42.fr;
		root ~/cursus/webserv/jullopez/;

		location /
		{
			index naviguation.html;
		}
	}

	server
	{
		listen 127.0.0.1:8080;
		server_name mde-prin.42.fr;
		root ~/cursus/webserv/mde-prin/;

		location /
		{
			index naviguation.html;
		}
	}

	client_max_body_size 8M;
}
